version: 2
jobs:
  deploy-staging:
    docker:
      - image: ruby:2.3.3-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy
          command: bundle exec cap staging deploy

workflows:
  version: 2
  deploy-staging:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: develop
